# Generated by Django 4.2.16 on 2025-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp1', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(upload_to='materials/'),
        ),
    ]
